### ISSUE TITLE
Line.IntersectRect not working correctly for rectangle with point (0;0)

### ISSUE THREAD

**Issue by slawekxs** [faiface/pixel#210] opened 2019-12-06 10:21 UTC
Hi,

running this test will show the issue 
```
func TestIntersectAt00(t *testing.T) {
	l := pixel.L(pixel.V(0, -10), pixel.V(0, 10))

	got := l.IntersectRect(pixel.R(-1, 0, 2, 2))
	if got.X != -1 || got.Y != 0 {
		t.Errorf("got '%s' want (-1, 0)", got)
	}
}
```

when intersection occurs at point 0,0 `IntersectRect` will return Vec that will point to last corner of the Rect instead of returning the shortest Vec

**Comment by delp** [comment] 2020-05-07 00:21
Interesting. I ran the test and I am seeing what you describe. I'll have to investigate further to make sure I understand the intended behavior. Thanks for the submission.

**Comment by bcvery1** [comment] 2020-05-07 08:01
@delp I'll have half an eye on this, as I originally wrote the line geometry code, therefore introduced the bug.  When implementing a fix it'll be much better to include the test case in the pre-existing table defined tests:
```go
func TestLine_IntersectRect(t *testing.T) {
	type fields struct {
		A pixel.Vec
		B pixel.Vec
	}
	type args struct {
		r pixel.Rect
	}
	tests := []struct {
		name   string
		fields fields
		args   args
		want   pixel.Vec
	}{
		{
			name:   "Line through rect vertically",
			fields: fields{A: pixel.V(0, 0), B: pixel.V(0, 10)},
			args:   args{r: pixel.R(-1, 1, 5, 5)},
			want:   pixel.V(-1, 0),
		},
		{
			name:   "Line through rect horizontally",
			fields: fields{A: pixel.V(0, 1), B: pixel.V(10, 1)},
			args:   args{r: pixel.R(1, 0, 5, 5)},
			want:   pixel.V(0, -1),
		},
		{
			name:   "Line through rect diagonally bottom and left edges",
			fields: fields{A: pixel.V(0, 0), B: pixel.V(10, 10)},
			args:   args{r: pixel.R(0, 2, 3, 3)},
			want:   pixel.V(-1, 1),
		},
		{
			name:   "Line through rect diagonally top and right edges",
			fields: fields{A: pixel.V(10, 0), B: pixel.V(0, 10)},
			args:   args{r: pixel.R(5, 0, 8, 3)},
			want:   pixel.V(-2.5, -2.5),
		},
		{
			name:   "Line with not rect intersect",
			fields: fields{A: pixel.V(0, 0), B: pixel.V(10, 10)},
			args:   args{r: pixel.R(20, 20, 21, 21)},
			want:   pixel.ZV,
		},
		{
			name:   "Line intersects at 0,0",
			fields: fields{A: pixel.V(-1, 0), B: pixel.V(2, 2)},
			args:   args{r: pixel.R(0, -10, 0, 10)},
			want:   pixel.V(-1, 0),
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			l := pixel.Line{
				A: tt.fields.A,
				B: tt.fields.B,
			}
			if got := l.IntersectRect(tt.args.r); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("Line.IntersectRect() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

Far busier at the moment than I'd like, but if I get some spare time, I'll try put some work into getting a fix for this (unless someone else gets to it first)

**Comment by delp** [comment] 2020-05-09 01:55
Thanks for checking in, help would be awesome.

**Closed** 2020-05-10 20:49 UTC
Labels: bug, help wanted
