### ISSUE TITLE
Panic when running create window example

### ISSUE THREAD

**Issue by Keithcat1** [faiface/pixel#206] opened 2019-11-13 17:27 UTC
I was messing around with the create window example. I eventually got it to compile, then iti gave this error.
panic: creating window failed: VersionUnavailable: WGL: A forward compatible Ope
nGL context requested but WGL_ARB_create_context is unavailable

goroutine 19 [running]:
main.run()
        C:/py/t.go:15 +0xdc
github.com/faiface/mainthread.Run.func1(0x571518, 0x12036080)
        C:/py/go/src/github.com/faiface/mainthread/mainthread.go:37 +0x1d
created by github.com/faiface/mainthread.Run
        C:/py/go/src/github.com/faiface/mainthread/mainthread.go:36 +0x89

Here's the code:
package main

import (
	"github.com/faiface/pixel"
	"github.com/faiface/pixel/pixelgl"
)

func run() {
	cfg := pixelgl.WindowConfig{
		Title:  "Pixel Rocks!",
		Bounds: pixel.R(0, 0, 1024, 768),
	}
	win, err := pixelgl.NewWindow(cfg)
	if err != nil {
		panic(err)
	}

	for !win.Closed() {
		win.Update()
	}
}

func main() {
	pixelgl.Run(run)
}
Any help would be appreciated!

**Comment by aerth** [comment] 2020-02-07 21:46
Looks like duplicate of #26

**Comment by delp** [comment] 2020-06-12 20:10
Yes, this seems like a duplicate.

**Closed by delp** 2020-06-12 20:10 UTC
Labels: duplicate
