### ISSUE TITLE
Monitor:   pixelgl.PrimaryMonitor()

### ISSUE THREAD

**Issue by xinkiknix** [faiface/pixel#67] opened 2017-11-07 13:16 UTC
When switching from fullscreen mode (Monitor:   pixelgl.PrimaryMonitor() in cfg) to any other window (alt-tab) (Windows 10)  I get following error
When running in windowed model all works fine

_panic: reflect: slice index out of range

goroutine 1 [running, locked to thread]:
reflect.Value.Index(0x549400, 0xc04d1b4b60, 0x97, 0x0, 0x549400, 0x2, 0xc045877cf8)
	C:/Go/src/reflect/value.go:871 +0x1eb
github.com/go-gl/gl/v3.3-core/gl.Ptr(0x549400, 0xc04d1b4b60, 0x549400)
	C:/Users/Johan/go/src/github.com/go-gl/gl/v3.3-core/gl/conversions.go:44 +0xe4
github.com/faiface/glhf.NewTexture(0x0, 0x0, 0x0, 0x6a7040, 0x0, 0x0, 0x0)
	C:/Users/Johan/go/src/github.com/faiface/glhf/texture.go:47 +0x125
github.com/faiface/glhf.NewFrame(0x0, 0x0, 0x0, 0x0)
	C:/Users/Johan/go/src/github.com/faiface/glhf/frame.go:37 +0x75
github.com/faiface/pixel/pixelgl.(*GLFrame).SetBounds.func1()
	C:/Users/Johan/go/src/github.com/faiface/pixel/pixelgl/glframe.go:35 +0x8b
github.com/faiface/mainthread.Call.func1()
	C:/Users/Johan/go/src/github.com/faiface/mainthread/mainthread.go:64 +0x2d
github.com/faiface/mainthread.Run(0x5a14d8)
	C:/Users/Johan/go/src/github.com/faiface/mainthread/mainthread.go:46 +0xf8
github.com/faiface/pixel/pixelgl.Run(0x5a14d8)
	C:/Users/Johan/go/src/github.com/faiface/pixel/pixelgl/run.go:32 +0x60
main.main()
	C:/Users/Johan/go/src/Quakes_1/Quakes_1.go:255 +0x34_

**Comment by faiface** [comment] 2017-11-07 16:59
This is a duplicate of #58 and #63, take a look at those issues. We still don't know what exactly causes this, so any further investigation is appreciated.

**Closed** 2017-11-07 16:59 UTC
Labels: duplicate

**Comment by xinkiknix** [comment] 2017-11-08 07:48
I will do some debugging ASAP

Op 7 nov. 2017 17:59 schreef "Michal Štrba" <notifications@github.com>:
